### PR TITLE
Demux at endpoints; operational concerns

### PR DESCRIPTION
**Pull request by martinthomson**

### CODE REVIEW

**Comment by rgwilton** [comment]
LGTM.

**Comment by rgwilton** [comment]
Actually, looking at a bit closer, perhaps consider:

"... endpoint and cooperating intermediaries to efficiently ..."

and perhaps make the Manageability reference explicitly to section 3.1 that covers identifying QUIC traffic.

**Comment by martinthomson** [comment]
Note that this is the second paragraph of the document.  I'd prefer not to pile too many unrelated concepts in at this point.  I think that it is OK to consider "cooperating intermediaries" to be implicit when we say "endpoint" when operating at this level of abstraction.  Toward the end, where manageability is cited, is a better place for that sort of detail.

I narrowed the citation to point to Section 3.1 as you suggested.

**Comment by zaheduzzaman** [comment]
I think this update addresses @rgwilton 's point in the telechat review.

**Pull request merged**
